# This is a basic workflow to help you get started with Actions

name: Deploy exercise alternativa 1
on: push
jobs:
    deploy_enfoque1:
    runs-on: ubuntu-latest
    steps:
      - name: obtener codigo
        uses: actions/checkout@v6
      - name: Instalar dependenciaas
        uses: npm ci
      - name: Lint
       uses: npm run lint
      - name: correr pruebas
        uses: npm run test
      - name: build codigo
        uses: npm run build
      - name: Despliegue
        uses: echo "simulando despliegue"
