# This is a basic workflow to help you get started with Actions

name: Deploy exercise alternativa 1
on: push
jobs:
    deploy_enfoque1:
        runs-on: ubuntu-latest
        steps:
          - name: obtener codigo
            uses: actions/checkout@v6
          - name: Instalar dependenciaas
            run: npm ci
          - name: Lint
            run: npm run lint
          - name: correr pruebas
            run: npm run test
          - name: build codigo
            run: npm run build
          - name: Despliegue
            run: echo "simulando despliegue"
